### ISSUE TITLE
submodule update fails from go-get

### ISSUE THREAD

**Issue by dolanor** [Roninkoi/LD44#1]
```
go get -v github.com/Roninkoi/LD44
github.com/Roninkoi/LD44 (download)
# cd /home/dolanor/go/src/github.com/Roninkoi/LD44; git submodule update --init --recursive
fatal: Pas de mise en correspondance du sous-module trouvé dans .gitmodules pour le chemin 'libs/go-gl/mathgl'
package github.com/Roninkoi/LD44: exit status 128
```
I have found this: https://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule
So it seems you added those deps as a submodules and maybe removed the .gitmodules, but still git created some gitlink to them pointing to nowhere. So I guess you should `git rm` them since it seems you use the import directly from GOPATH.
Maybe you can also use go modules.

**Comment by Roninkoi** [comment]
Thanks, I removed the libs as those were quite unnecessary
